### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [nonsensicalthinking/planttracker#34]
Hi,

Since this app is GNU GPLv3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

You will need to create [tagged releases](https://help.github.com/articles/creating-releases/), with a consistent name for each release (for example `1.0` then `2.0` etc...)

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by nonsensicalthinking** [comment]
Thanks for mentioning it. I'll have a look at f-droid and get back to you, the app still has a bit of work left to be completed.

**Comment by Poussinou** [comment]
It should be pretty easy, since you don't use any proprietary library nor binary blob.

Ping me when you want to include it, I could help you

**Comment by IzzySoft** [comment]
F-Droid maintainer here. Do you need help with this task? A quick glance at your gradle looks like it makes a good candidate for F-Droid.

**Comment by nonsensicalthinking** [comment]
Thanks for your interest, Izzy.  I anticipate working on this project more in the coming months and I will revisit this and make a decision at that time.

**Comment by IzzySoft** [comment]
Good to know! Be welcome to ping @Poussinou or me if you need help/advice.

**Comment by goyalyashpal** [comment]
@nonsensicalthinking pinging for revisit :) **

**Comment by IzzySoft** [comment]
Right – there were 24 months "coming" (and going) meanwhile. Did you have a chance, @nonsensicalthinking?
